POST http://localhost:8080/api/appointment
Content-Type: application/x-www-form-urlencoded

patientId=6&status=false&doctorId=9&termId=1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.headers.valueOf("Location")!= null, "Invalid Location");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
  client.global.set("newSlotUrl", response.headers.valueOf("Location"));
  client.global.set("slotId", response.body["slotId"]);
});
%}


###
POST http://localhost:8080/api/appointment
Content-Type: application/x-www-form-urlencoded

patientId=2&consultancyFees=500&status=true&creationDate=2019-10-31T01:30:00&doctorId=3&termId=2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.headers.valueOf("Location")!= null, "Invalid Location");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
  client.global.set("newSlotUrl", response.headers.valueOf("Location"));
  client.global.set("slotId", response.body["slotId"]);
});
%}


###
DELETE http://localhost:8080/api/appointment/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/appointment

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/appointment?appointmentId=7

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/appointment?patientId=7

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/appointment?doctorId=8

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
PATCH http://localhost:8080/api/appointment/1/active

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###